// login
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
// projectss
export const FETCH_PROJECTS = "FETCH_PROJECTS"
export const FETCH_PROJECTS_SUCCEEDED = "FETCH_PROJECTS_SUCCEEDED"
export const FETCH_PROJECTS_FAILED = "FETCH_PROJECTS_FAILED"
// kpi
export const FETCH_KPI = "FETCH_KPI"
export const FETCH_KPI_SUCCEEDED = "FETCH_KPI_SUCCEEDED"
export const FETCH_KPI_FAILED = "FETCH_KPI_FAILED"
// pfm
export const ADD_PFM = "ADD_PFM"
export const ADD_PFM_SUCCEEDED = "ADD_PFM_SUCCEEDED"
export const ADD_PFM_FAILED = "ADD_PFM_FAILED"